CREATE TABLE IF NOT EXISTS publications (
  id TEXT PRIMARY KEY,
  offer_id TEXT NOT NULL REFERENCES offers(id) ON DELETE CASCADE,
  group_id TEXT NOT NULL REFERENCES promo_groups(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'READY',
  scheduled_at TIMESTAMPTZ,
  published_at TIMESTAMPTZ,
  clicks INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)
