export const access='public';

export default function(req,res){
  res.setHeader('Content-Type','text/html; charset=utf-8');
  res.send(`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Radar Promo Brasil</title><meta name="description" content="Organize ofertas de afiliados, imagens, filas e grupos em um único painel."><link rel="stylesheet" href="/inicio.css" /></head><body><header><div class="wrap nav"><a class="brand" href="/inicio"><i>RPB</i>Radar Promo Brasil</a><nav class="links"><a href="#como">Como funciona</a><a href="#recursos">Recursos</a><a href="#planos">Planos</a><a href="#faq">FAQ</a><a class="btn ghost" href="/">Entrar</a></nav></div></header>
  <main><section class="hero"><div class="wrap grid"><div><div class="tag">Operação de afiliados em um só lugar</div><h1>Transforme ofertas em publicações organizadas.</h1><p>Centralize Amazon, Shopee e Mercado Livre, prepare mensagens com imagem, direcione por categoria e acompanhe filas e resultados.</p><div class="actions"><a class="btn" href="/">Acessar painel</a><a class="btn ghost" href="#como">Ver como funciona</a></div></div><div class="panel"><div><b>3</b><br>marketplaces preparados</div><div><b>24/7</b><br>estrutura para monitoramento</div><div><b>1–30 min</b><br>intervalos configuráveis</div></div></div></section>
  <section class="section" id="como"><div class="wrap"><h2>Do link ao grupo certo</h2><p class="lead">O Radar valida dados essenciais antes de enfileirar uma promoção. Integrações externas só são ativadas depois da autorização e de um teste real.</p><div class="flow"><div class="step"><small>01</small><h3>Capturar</h3><p>Receba uma oferta autorizada.</p></div><div class="step"><small>02</small><h3>Preparar</h3><p>Imagem, preço, categoria e CTA.</p></div><div class="step"><small>03</small><h3>Organizar</h3><p>Fila, prioridade e horário.</p></div><div class="step"><small>04</small><h3>Distribuir</h3><p>Envio pelo conector escolhido.</p></div></div></div></section>
  <section class="section alt" id="recursos"><div class="wrap"><h2>Recursos da plataforma</h2><p class="lead">Uma base modular para operar com controle e rastreabilidade.</p><div class="cards"><div class="card"><span>🔗</span><h3>Links e SubIDs</h3><p>Regras separadas para Amazon, Shopee e Mercado Livre, com identificação por grupo.</p></div><div class="card"><span>🖼️</span><h3>Imagem no envio</h3><p>A publicação mantém imagem, mensagem e link no mesmo pacote.</p></div><div class="card"><span>📋</span><h3>Filas inteligentes</h3><p>Agendamento, intervalo, prioridade e recuperação de falhas.</p></div><div class="card"><span>👥</span><h3>Gestão de leads</h3><p>Entradas, saídas, leads únicos, retenção e alerta de lotação.</p></div><div class="card"><span>📱</span><h3>Múltiplas conexões</h3><p>Estrutura de prioridade e fallback entre números cadastrados.</p></div><div class="card"><span>🛍️</span><h3>Vitrine pública</h3><p>Ofertas aprovadas reunidas em uma página compartilhável.</p></div></div></div></section>
  <section class="section" id="planos"><div class="wrap"><h2>Planos simples</h2><p class="lead">Os preços e o provedor de pagamento serão ativados somente após a configuração comercial.</p><div class="plans"><div class="card"><h3>Teste</h3><div class="price">7 dias</div><div class="list">Painel completo<br>Configuração das lojas<br>Vitrine de ofertas</div></div><div class="card"><h3>Pro</h3><div class="price">A definir</div><div class="list">Filas e agendamentos<br>Gestão de leads<br>Até 3 grupos</div></div><div class="card"><h3>Escala</h3><div class="price">A definir</div><div class="list">Mais grupos<br>Múltiplas conexões<br>Operação assistida</div></div></div></div></section>
  <section class="section alt faq" id="faq"><div class="wrap"><h2>Perguntas frequentes</h2><details><summary>Os envios já funcionam automaticamente?</summary><p>O envio assistido funciona. O envio externo depende da conexão autorizada do WhatsApp e do fluxo n8n validado.</p></details><details><summary>O sistema garante comissão?</summary><p>Não. A atribuição depende das regras, cookies, elegibilidade e relatórios de cada marketplace.</p></details><details><summary>Posso usar vários números?</summary><p>A estrutura de múltiplas conexões e fallback está disponível; cada número precisa ser autorizado no provedor escolhido.</p></details><details><summary>O sistema evita bloqueios?</summary><p>Nenhum sistema pode garantir isso. É necessário respeitar consentimento, limites, políticas e regras do WhatsApp.</p></details></div></section>
  <section class="section"><div class="wrap cta"><h2>Organize sua operação de afiliados</h2><p>Entre no painel para configurar suas lojas, grupos e vitrine.</p><a class="btn ghost" href="/">Acessar painel</a></div></section></main>
  <footer><div class="wrap foot"><div><b>Radar Promo Brasil</b><p>Automação responsável para afiliados.</p></div><div><a href="/privacidade">Privacidade</a> · <a href="/termos">Termos de uso</a> · <button class="footer-privacy-button" data-cookie-open>Cookies</button></div></div></footer>
  <div class="cookie" id="cookie"><p>🍪 Usamos armazenamento essencial para o funcionamento e, somente com sua escolha, recursos de análise. Consulte nossa Política de Privacidade.</p><button class="btn ghost" data-cookie-choice="essential">Apenas essenciais</button><button class="btn" data-cookie-choice="all">Aceitar todos</button></div><script src="/inicio.js" defer></script></body></html>`);
}
