import { db } from 'hatchable';
export const access='member';
export const methods=['GET','POST'];
const uid=()=>crypto.randomUUID(),text=(v,n=200)=>String(v??'').trim().slice(0,n),stores=['AMAZON','SHOPEE','MERCADO_LIVRE'];
async function account(m){return (await db.query('SELECT id FROM accounts WHERE owner_member_id=$1',[String(m.id)])).rows[0]}
export default async function(req,res){
 if(!req.member)return res.status(401).json({error:'Não autorizado.'});const correlationId=crypto.randomUUID();
 try{const a=await account(req.member);if(!a)return res.status(412).json({error:'Abra o painel para inicializar sua conta.'});
  if(req.method==='POST'){const b=req.body||{},marketplace=text(b.marketplace,30),externalId=text(b.externalId,160),status=text(b.status,20)||'PENDING';if(!stores.includes(marketplace)||!externalId||!['PENDING','APPROVED','CANCELLED','PAID'].includes(status))return res.status(400).json({error:'Venda inválida.'});const offerId=text(b.offerId,100)||null,groupId=text(b.groupId,100)||null;if(offerId&&!(await db.query('SELECT id FROM offers WHERE id=$1 AND account_id=$2',[offerId,a.id])).rows.length)return res.status(400).json({error:'Oferta não pertence à conta.'});if(groupId&&!(await db.query('SELECT id FROM promo_groups WHERE id=$1 AND account_id=$2',[groupId,a.id])).rows.length)return res.status(400).json({error:'Grupo não pertence à conta.'});const gross=Math.max(0,Math.round(Number(b.gross||0)*100)),commission=Math.max(0,Math.round(Number(b.commission||0)*100)),orderedAt=new Date(b.orderedAt||Date.now());if(Number.isNaN(orderedAt.getTime()))return res.status(400).json({error:'Data inválida.'});await db.query("INSERT INTO affiliate_sales(id,account_id,external_id,marketplace,offer_id,group_id,subid,gross_cents,commission_cents,status,ordered_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(account_id,marketplace,external_id) DO UPDATE SET offer_id=EXCLUDED.offer_id,group_id=EXCLUDED.group_id,subid=EXCLUDED.subid,gross_cents=EXCLUDED.gross_cents,commission_cents=EXCLUDED.commission_cents,status=EXCLUDED.status,ordered_at=EXCLUDED.ordered_at,updated_at=now()",[uid(),a.id,externalId,marketplace,offerId,groupId,text(b.subid,120),gross,commission,status,orderedAt.toISOString()]);return res.json({ok:true})}
  const days=Math.max(1,Math.min(365,Number(req.query.days)||30)),p=[a.id,days];
  const [summary,category,groups,platforms,daily,top,delivery,channels]=await Promise.all([
   db.query("SELECT (SELECT count(*)::int FROM publications WHERE account_id=$1 AND status='PUBLISHED' AND published_at>=now()-($2||' days')::interval) shared,(SELECT count(*)::int FROM click_events WHERE account_id=$1 AND occurred_at>=now()-($2||' days')::interval) clicks,(SELECT count(*)::int FROM affiliate_sales WHERE account_id=$1 AND status<>'CANCELLED' AND ordered_at>=now()-($2||' days')::interval) sales,(SELECT COALESCE(sum(gross_cents),0)::bigint FROM affiliate_sales WHERE account_id=$1 AND status<>'CANCELLED' AND ordered_at>=now()-($2||' days')::interval) revenue,(SELECT COALESCE(sum(commission_cents),0)::bigint FROM affiliate_sales WHERE account_id=$1 AND status<>'CANCELLED' AND ordered_at>=now()-($2||' days')::interval) commission",p),
   db.query("SELECT c.name,count(DISTINCT p.id)::int shared,count(DISTINCT ce.id)::int clicks,count(DISTINCT s.id)::int sales,COALESCE(sum(DISTINCT s.commission_cents),0)::bigint commission FROM categories c LEFT JOIN offers o ON o.category_id=c.id AND o.account_id=c.account_id LEFT JOIN publications p ON p.offer_id=o.id AND p.account_id=c.account_id AND p.published_at>=now()-($2||' days')::interval LEFT JOIN click_events ce ON ce.publication_id=p.id AND ce.occurred_at>=now()-($2||' days')::interval LEFT JOIN affiliate_sales s ON s.offer_id=o.id AND s.account_id=c.account_id AND s.status<>'CANCELLED' AND s.ordered_at>=now()-($2||' days')::interval WHERE c.account_id=$1 GROUP BY c.id,c.name ORDER BY commission DESC,clicks DESC",p),
   db.query("SELECT g.id,g.name,g.platform,count(DISTINCT p.id)::int shared,count(DISTINCT ce.id)::int clicks,count(DISTINCT s.id)::int sales,COALESCE(sum(DISTINCT s.commission_cents),0)::bigint commission,g.members,g.capacity FROM promo_groups g LEFT JOIN publications p ON p.group_id=g.id AND p.account_id=g.account_id AND p.published_at>=now()-($2||' days')::interval LEFT JOIN click_events ce ON ce.publication_id=p.id AND ce.occurred_at>=now()-($2||' days')::interval LEFT JOIN affiliate_sales s ON s.group_id=g.id AND s.account_id=g.account_id AND s.status<>'CANCELLED' AND s.ordered_at>=now()-($2||' days')::interval WHERE g.account_id=$1 GROUP BY g.id,g.name,g.platform,g.members,g.capacity ORDER BY commission DESC,clicks DESC",p),
   db.query("WITH st(name) AS (VALUES('AMAZON'),('SHOPEE'),('MERCADO_LIVRE')) SELECT st.name,count(DISTINCT p.id)::int shared,count(DISTINCT ce.id)::int clicks,count(DISTINCT s.id)::int sales,COALESCE(sum(DISTINCT s.gross_cents),0)::bigint revenue,COALESCE(sum(DISTINCT s.commission_cents),0)::bigint commission FROM st LEFT JOIN offers o ON upper(replace(o.source,' ','_'))=st.name AND o.account_id=$1 LEFT JOIN publications p ON p.offer_id=o.id AND p.published_at>=now()-($2||' days')::interval LEFT JOIN click_events ce ON ce.publication_id=p.id AND ce.occurred_at>=now()-($2||' days')::interval LEFT JOIN affiliate_sales s ON s.marketplace=st.name AND s.account_id=$1 AND s.status<>'CANCELLED' AND s.ordered_at>=now()-($2||' days')::interval GROUP BY st.name ORDER BY commission DESC,clicks DESC",p),
   db.query("WITH dates AS (SELECT generate_series(current_date-($2::int-1),current_date,'1 day')::date AS report_date) SELECT dates.report_date AS day,count(DISTINCT ce.id)::int clicks,count(DISTINCT s.id)::int sales,COALESCE(sum(DISTINCT s.commission_cents),0)::bigint commission FROM dates LEFT JOIN click_events ce ON ce.account_id=$1 AND ce.occurred_at::date=dates.report_date LEFT JOIN affiliate_sales s ON s.account_id=$1 AND s.status<>'CANCELLED' AND s.ordered_at::date=dates.report_date GROUP BY dates.report_date ORDER BY dates.report_date",p),
   db.query("SELECT o.id,o.title,o.source,count(DISTINCT p.id)::int shared,count(DISTINCT ce.id)::int clicks,count(DISTINCT s.id)::int sales,COALESCE(sum(DISTINCT s.commission_cents),0)::bigint commission FROM offers o LEFT JOIN publications p ON p.offer_id=o.id AND p.published_at>=now()-($2||' days')::interval LEFT JOIN click_events ce ON ce.publication_id=p.id AND ce.occurred_at>=now()-($2||' days')::interval LEFT JOIN affiliate_sales s ON s.offer_id=o.id AND s.status<>'CANCELLED' AND s.ordered_at>=now()-($2||' days')::interval WHERE o.account_id=$1 GROUP BY o.id,o.title,o.source ORDER BY commission DESC,clicks DESC LIMIT 10",p),
   db.query("SELECT status,count(*)::int total FROM publications WHERE account_id=$1 AND created_at>=now()-($2||' days')::interval GROUP BY status ORDER BY total DESC",p),
   db.query("SELECT g.platform AS name,count(DISTINCT p.id)::int shared,count(DISTINCT ce.id)::int clicks,count(DISTINCT s.id)::int sales,COALESCE(sum(DISTINCT s.commission_cents),0)::bigint commission FROM promo_groups g LEFT JOIN publications p ON p.group_id=g.id AND p.account_id=g.account_id AND p.published_at>=now()-($2||' days')::interval LEFT JOIN click_events ce ON ce.publication_id=p.id AND ce.occurred_at>=now()-($2||' days')::interval LEFT JOIN affiliate_sales s ON s.group_id=g.id AND s.account_id=g.account_id AND s.status<>'CANCELLED' AND s.ordered_at>=now()-($2||' days')::interval WHERE g.account_id=$1 GROUP BY g.platform ORDER BY commission DESC,clicks DESC",p)
  ]);
  const s=summary.rows[0],clicks=Number(s.clicks),sales=Number(s.sales),revenue=Number(s.revenue),commission=Number(s.commission);return res.json({days,summary:{shared:Number(s.shared),clicks,sales,revenue,commission,conversionRate:clicks?Number((sales*100/clicks).toFixed(2)):0,averageTicket:sales?Math.round(revenue/sales):0,averageCommission:sales?Math.round(commission/sales):0},byCategory:category.rows,byGroup:groups.rows,byPlatform:platforms.rows,byChannel:channels.rows,daily:daily.rows,topOffers:top.rows,delivery:delivery.rows});
 }catch(e){console.error('api/reports',correlationId,e);return res.status(500).json({error:'Não foi possível gerar os relatórios.',correlationId})}
}
